describe('Admin Integration Testing', () => {
    it('Visits the app root url', () => {
        cy.visit('http://localhost:8080')
        cy.get('.login-div h1').contains('Sign in to your account')
    })
    it('Admin logs in', () => {
        cy.get('#userName').type('jeremiahAdmin')
        cy.get('#password').type('jeremiahAdmin')
        cy.get('button').click()
    })
    it('Admin is directed to Admin Page and displays correct buttons', () => {
        cy.get('.buttonLink:first').contains('Upload Lesson Video')
        cy.get('.buttonDeleteLink').contains('Delete Lesson')
        cy.get('.buttonLink:last').contains('Create Video Timestamps and Questions')
        cy.get('.buttonLink:first').click()
    })
    it('Admin has the option to upload a video', () => {
        cy.contains('label', "Upload Video File:")
        cy.contains('label', 'Name of Video:')
        cy.contains('label', 'Upload Video')
        cy.get('.button').click()
    })
    it('Admin can select a video to delete', () => {
        cy.get('#userName').type('jeremiahAdmin')
        cy.get('#password').type('jeremiahAdmin')
        cy.get('button').click()
        cy.get('.buttonDeleteLink').click()
        cy.contains('h4', "Select Lesson to Delete:")
        cy.contains('p', 'View Video Before Deletion:')
        cy.get('.nav-link:last').click()
    })
    it('Admin selects yes or no to confirm deletion of video', () => {
        cy.contains('header', "Lesson Deletion")
        cy.contains('p', 'Are you sure you wish to delete this lesson?')
        cy.get('.btn-green:last').click()
        cy.get('.button').click()
    })
    it('Admin clicks on `assign timestamps and questions to a video` link and sees the available videos', () => {
        cy.get('#userName').type('jeremiahAdmin')
        cy.get('#password').type('jeremiahAdmin')
        cy.get('button').click()
        cy.get('.buttonLink:last').click()
        cy.get('.nav-link').its('length').should('be.gte', 1)
    })
    it('Admin can add a timestamp and a question', () => {
        cy.get('.lesson-img:last').click()
        cy.contains('div', 'Add Timestamp Here')
        cy.get('#add-timestamp-button').click()
        cy.get('#assign-activity-button:first').click()
        cy.contains('header', 'Assign New Activity')
        cy.get('.btn-green').click()
        cy.get('#question-text').type('What is the call?')
        cy.get('#answer-one').type('Traveling')
        cy.get('#answer-two').type('Double Dribble')
        cy.get('.btn-green:first').click()
    })
    it('Admin seees the newly added activity and can choose to save or remove it', () => {
        cy.contains('div', '00:00')
        cy.get('#delete-timestamp-button:first').click()
    })  
    it('Admin logs out', () => {
        cy.get(".button").click()
    })  
})