describe('Instructor Integration Testing', () => {
    it('Visits the app root url', () => {
        cy.visit('http://localhost:8080')
        cy.get('.login-div h1').contains('Sign in to your account')
    })  
    it('Instructor logs in', () => {
        cy.get('#userName').type('testInstructor123')
        cy.get('#password').type('testInstructor123')
        cy.get('button').click()
    })
    it('Instructor is directed to instructor page', () => {
        cy.get('.buttonLinks:first').contains('Create a Classroom')
        cy.get('.buttonLinksSecond').contains('Create Video Timestamps and Questions')
        cy.get('.buttonLinks:last').contains('Update Class')
        cy.get('.buttonLinksSecond').click()
    })
    it('Instructor can access and use assignTimestamps page', () => {
        cy.get('.nav-link').its('length').should('be.gte', 1)
        cy.get('.lesson-img:last').click()
        cy.contains('div', 'Add Timestamp Here')
        cy.get('#add-timestamp-button').click()
        cy.get('#assign-activity-button:first').click()
        cy.contains('header', 'Assign New Activity')
        cy.get('.btn-green').click()
        cy.get('#question-text').type('What is the call?')
        cy.get('#answer-one').type('Traveling')
        cy.get('#answer-two').type('Double Dribble')
        cy.get('.btn-green:first').click()
        cy.contains('div', '00:00')
        cy.get('#delete-timestamp-button:first').click()
        cy.get(".button").click()
    })
    it('Instructor can add students to class and create a class', () => {
        cy.get('#userName').type('testInstructor123')
        cy.get('#password').type('testInstructor123')
        cy.get('button').click()
        cy.get('.buttonLinks:first').click()
        cy.contains('h3', 'Classroom Creation')
        cy.get('#className').type('TestClass123')
        cy.get('.nav-link:last').click()
        cy.contains('div', 'Selected Students')
        cy.get('.studentName').its('length').should('eq', 1)
        cy.get(".button").click()
    })  
    it('Instructor can see their created classes', () => {
        cy.get('#userName').type('testInstructor123')
        cy.get('#password').type('testInstructor123')
        cy.get('button').click()
        cy.get('.buttonLinks:last').click()
        cy.contains('h1', 'Update Your Classes')
        cy.contains('div', 'TestClass123')
    })  
    it('Instructor can add videos to their class', () => {
        cy.get('.updateButton:last').click()
        cy.contains('div', 'Update Lessons your Students Can Take')
        cy.get('.addVideo').its('length').should('be.gte', 1)
        cy.get('.addVideo:first').click()
        cy.contains('p', '1 Video Lessons')
    })  
    it('Instructor can remove videos from their class', () => {
        cy.get('.updateButton:last').click()
        cy.get('.removeVideo').its('length').should('eq', 1)
        cy.get('.removeVideo:first').click()
        cy.contains('p', '0 Video Lessons')
    })  
    it('Instructor can add/remove students to their class', () => {
        cy.get('.updateButton:first').click()
        cy.get('.removeStudent').its('length').should('eq', 1)
        cy.get('.removeStudent:first').click()
        cy.contains('p', '0 Students')
        cy.get('.updateButton:first').click()
        cy.get('.addStudent').its('length').should('be.gte', 1)
        cy.get('.addStudent:first').click()
        cy.contains('p', '1 Students')
        cy.get('.button').click()
    })  
})